name = "wwwtom"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Main worker script
main = ".output/server/index.mjs"

[[kv_namespaces]]
binding = "TOM_RATE_LIMIT_KV"
id = "b3800e793bb94ddab775776d600e1c64"
preview_id = "bb85565a5ea045e2aa00fbdc5b3153b4"

# WASM bindings
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

# Build configuration
[build]
command = "bun run build"

[observability.logs]
enabled = true

# Static assets configuration for Git LFS files
# This will serve your public/ directory files including those managed by Git LFS
[assets]
directory = ".output/public"

# Environment variables
[vars]
NODE_ENV = "production"
