export const TA_TO_REGION: Record<string, string> = {
  "Far North District": "Northland",
  "Whangarei District": "Northland",
  "Kaipara District": "Northland",
  Auckland: "Auckland",
  "Thames-Coromandel District": "Waikato",
  "Hauraki District": "Waikato",
  "Waikato District": "Waikato",
  "Matamata-Piako District": "Waikato",
  "Hamilton City": "Waikato",
  "Waipa District": "Waikato",
  "Otorohanga District": "Waikato",
  "South Waikato District": "Waikato",
  "Waitomo District": "Waikato",
  "Taupo District": "Waikato",
  "Western Bay of Plenty District": "Bay of Plenty",
  "Tauranga City": "Bay of Plenty",
  "Rotorua District": "Bay of Plenty",
  "Whakatane District": "Bay of Plenty",
  "Kawerau District": "Bay of Plenty",
  "Opotiki District": "Bay of Plenty",
  "Gisborne District": "Gisborne",
  "Wairoa District": "Hawke's Bay",
  "Hastings District": "Hawke's Bay",
  "Napier City": "Hawke's Bay",
  "Central Hawke's Bay District": "Hawke's Bay",
  "New Plymouth District": "Taranaki",
  "Stratford District": "Taranaki",
  "South Taranaki District": "Taranaki",
  "Ruapehu District": "Manawatu-Whanganui",
  "Whanganui District": "Manawatu-Whanganui",
  "Rangitikei District": "Manawatu-Whanganui",
  "Manawatu District": "Manawatu-Whanganui",
  "Palmerston North City": "Manawatu-Whanganui",
  "Tararua District": "Manawatu-Whanganui",
  "Horowhenua District": "Manawatu-Whanganui",
  "Kapiti Coast District": "Wellington",
  "Porirua City": "Wellington",
  "Upper Hutt City": "Wellington",
  "Lower Hutt City": "Wellington",
  "Wellington City": "Wellington",
  "Masterton District": "Wellington",
  "Carterton District": "Wellington",
  "South Wairarapa District": "Wellington",
  "Tasman District": "Tasman",
  "Nelson City": "Nelson",
  "Marlborough District": "Marlborough",
  "Buller District": "West Coast",
  "Grey District": "West Coast",
  "Westland District": "West Coast",
  "Kaikoura District": "Canterbury",
  "Hurunui District": "Canterbury",
  "Waimakariri District": "Canterbury",
  "Christchurch City": "Canterbury",
  "Selwyn District": "Canterbury",
  "Ashburton District": "Canterbury",
  "Timaru District": "Canterbury",
  "Mackenzie District": "Canterbury",
  "Waimate District": "Canterbury",
  "Waitaki District": "Otago",
  "Central Otago District": "Otago",
  "Queenstown-Lakes District": "Otago",
  "Dunedin City": "Otago",
  "Clutha District": "Otago",
  "Southland District": "Southland",
  "Gore District": "Southland",
  "Invercargill City": "Southland",
  "Chatham Islands Territory": "Chatham Islands",
};

export const getRegion = (ta: string | null): string | null =>
  ta ? (TA_TO_REGION[ta] ?? null) : null;
