name = "{{name}}"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Build using OpenNext
[build]
command = "bun run build"

main = ".open-next/worker.js"

[observability.logs]
enabled = true

[vars]
NODE_ENV = "production"
