name = "{{name}}"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration for Astro
[build]
command = "bun run build"

main = "./dist/_worker.js"

[observability.logs]
enabled = true

[vars]
NODE_ENV = "production"
