/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Regenerate with: pnpm --filter @tom/db generate
 */

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface GuestbookEntries {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  fediverse_instance: string;
  fediverse_username: string;
  id: Generated<number>;
  message: string;
  updated_at: Generated<Timestamp>;
}

export interface OauthSessions {
  client_id: string;
  client_secret: string;
  code_verifier: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  fediverse_instance: string;
  id: Generated<number>;
  session_token: string;
  state: string;
}

export interface DB {
  guestbook_entries: GuestbookEntries;
  oauth_sessions: OauthSessions;
}

/** Alias keeping the historic @tom/types/db import path stable. */
export type Database = DB;
