// Generated by wrangler types
// After adding/changing bindings in wrangler.jsonc, regenerate with:
//   wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts

declare namespace Cloudflare {
  interface Env {
    D1: D1Database;
    ASSETS: Fetcher;
  }
}

interface CloudflareEnv extends Cloudflare.Env {}
