import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";

const FONTS = [
  {
    name: "LIBRE_CASLON",
    url: "https://cdn.tom.so/LibreCaslonCondensed-Regular.ttf",
    sha256: "ea0e022ef85781261e928ccfcb5aeed3b2fbc8f0100ec5191e743953e3ca3666",
  },
  {
    name: "SOLWAY",
    url: "https://cdn.jsdelivr.net/fontsource/fonts/solway@5.3.0/latin-400-normal.woff2",
    sha256: "37adaaf17a4e053e13513fe2c9c5111d2ef7cb9f3aa31274b5793fd520deaa42",
  },
] as const;

const define = (name: string, base64: string): string => `const ${name}_BASE64 =\n  "${base64}";`;

const out = ["// Generated by apps/api/scripts/generate-fonts.ts — do not edit by hand."];

for (const font of FONTS) {
  const response = await fetch(font.url);
  if (!response.ok) throw new Error(`Failed to fetch ${font.url}: ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  const digest = createHash("sha256").update(bytes).digest("hex");
  if (digest !== font.sha256) throw new Error(`Hash mismatch for ${font.url}: ${digest}`);
  out.push("", define(font.name, Buffer.from(bytes).toString("base64")));
}

out.push(
  "",
  "const bytesFromBase64 = (base64: string): ArrayBuffer =>",
  "  Uint8Array.from(atob(base64), (char) => char.charCodeAt(0)).buffer;",
  "",
  "export const libreCaslonFontBytes = (): ArrayBuffer => bytesFromBase64(LIBRE_CASLON_BASE64);",
  "export const solwayFontBytes = (): ArrayBuffer => bytesFromBase64(SOLWAY_BASE64);",
  "",
);

await writeFile(
  new URL("../src/services/fonts.generated.ts", import.meta.url),
  `${out.join("\n")}`,
);
console.log("Wrote apps/api/src/services/fonts.generated.ts");
