name: Bombardier performance stress test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - "*/*"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: "1.23"
          cache: true

      - name: Install bombardier
        run: go install github.com/codesenberg/bombardier/

      - name: Run load test on home
        run: bombardier -c 20000 -d 10s https://tom.so

      - name: Run load test on works directory
        run: bombardier -c 20000 -d 10s https://tom.so/works

      - name: Run load test on blog posts
        run: bombardier -c 20000 -d 10s https://tom.so/posts
