name: Release

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: ./.github/actions/setup

      - name: Fetch all tags and ensure branch is up to date
        run: |
          git fetch --tags
          git checkout dev
          git pull origin dev

      - name: Build
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run semantic-release
